name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  schedule:
  - cron: "52 23 * * 2"
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r14153"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: ${{ matrix.josm-revision }}
      perform-revision-tagging: ${{ github.repository == 'JOSM/continuos-download' && github.ref_type == 'branch' && github.ref_name == 'master' && github.event_name != 'schedule' && github.event_name != 'pull_request' && matrix.josm-revision == 'r14153' }}
    secrets: inherit
    permissions:
      checks: write
      contents: write
      deployments: write
